# .github/workflows/build_and_publish.yml

name: Build and Publish to PyPI
on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: ASDF Parse
        uses: kota65535/github-asdf-parse-action@v1.1.0
        id: versions

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "${{ steps.versions.outputs.python }}"

      - name: Install Poetry
        uses: Gr1N/setup-poetry@v8
        with:
          poetry-version: "${{ steps.versions.outputs.poetry }}"

      - name: Install dependencies
        run: |
          poetry install

      - name: Make sure it runs
        run: |
          poetry run clean-workspace --help

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token}}
          version-file: './pyproject.toml'
          version-path: 'tool.poetry.version'
          fallback-version: "1.0.0"
          output-file: 'CHANGELOG.md'

      # NOTE must run after versioning otherwise the right version won't be pushed
      - name: Build distribution package
        run: |
          poetry build

      - name: Publish to PyPI
        run: |
          # `gh secret set PYPI_API_TOKEN --app actions --body $PYPI_API_TOKEN`
          poetry publish -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}